services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - project_network

  nginx:
    image: nginx:alpine
    container_name: project_nginx
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - project_network

  mysql:
    image: mysql:8.0
    container_name: project_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - project_dbdata:/var/lib/mysql
    networks:
      - project_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "5002:80"
    depends_on:
      - mysql
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  project_dbdata: